### ISSUE TITLE
"특정 매치의 상세 정보 조회" 에서 플레이어 정보가 null로 반환됨

### ISSUE THREAD

**Issue by huhani** [mschadev/kartrider-open-api-docs#13]
**정보**  
발생한 시간:  2022-01-07 11:23
API URL:  https://api.nexon.co.kr/kart/v1.0/matches/002b001341e6ed57
API Query:   

**문제**
![image](https://user-images.githubusercontent.com/14067713/148480903-f58b4e19-85e0-49ee-9301-54bedaacabd1.png)

**Comment by mschadev** [comment]
추가로, 한쪽 팀(teamId `1` 혹은 `2`)에서만 `players`가 null로 뜨는 경우도 있습니다.
API 라이브러리 개발시 참고 부탁드립니다.
